### ISSUE TITLE
vector2euler?

### ISSUE THREAD

**Issue by MoritzWM** [alisterburt/eulerangles#10]
Hi Alister,

I'm writing a [small package](https://github.com/Chlanda-Lab/napari-surface-picker) to allow particle picking on surfaces, similar to Dynamo's surface models. For this, it would be useful to convert vectors to euler angles.

Would you be interested to incorporate this into your package? I haven't started writing this yet but could create a pull request once I have something.

**Comment by alisterburt** [comment]
Hey @MoritzWM ! I actually don't really use this package any more, I default to scipy to stick with the ecosystem 

I've implemented this before elsewhere and the general outline is
- take the cross product of your z and a random vector not aligned with z to get a perpendicular vector in the xy plan
- take another cross product to get the third vector


You have to be careful about that random vector not aligning with your z vector and the order of elements in the second cross product producing a correctly oriented coordinate system

**Comment by alisterburt** [comment]
@MoritzWM you should check out 'surforama' - looks like you are trying similar things!

**Comment by MoritzWM** [comment]
Hi Alister,

wow surforama looks very nice, thanks for the hint! However it's not exactly what I'm planning to do.

I didn't quite understand your calculation method. I implemented it quite differently now (see [here](https://github.com/Chlanda-Lab/napari-surface-picker/blob/e7b9d774becef908efcaa5a747c97c7d851c75f9/src/napari_surface_picker/utils.py), though getting everything right did take some trial and error.

**Comment by alisterburt** [comment]
@MoritzWM nice that you got it working! The difference between implementations is that you are directly calculating Euler angles whereas I am constructing the three orthonormal vectors that make up the rotated coordinate system - different approaches that yield the same result :-)

In case this is news for you: the columns of a rotation matrix are the rotated basis vectors... this means you can construct a rotation matrix by putting three orthonormal vectors as the columns of a new matrix
