### ISSUE TITLE
Could we add sdist files to pypi?

### ISSUE THREAD

**Issue by goanpeca** [alisterburt/eulerangles#7]
Hi @alisterburt 

Currently https://pypi.org/project/eulerangles/#files only uploaded wheels for the latest version. We could use the github tarball  form releases, but it less convenient when dealing with conda packages.

Do you thing you could do a minor release to include the sdist files and not just the wheels?

Thanks!

**Comment by alisterburt** [comment]
Sorry for taking some time to get to this - v1.0.2 now available on PyPI with sdist files (and I know a bit more about packaging than I used to! 🙂 )

Closing but please reopen if I've made a mistake somewhere
